#Requires -Version 5.1
<#
.SYNOPSIS
    Azure Virtual Desktop (AVD) for Hybrid Environments - Session Host Onboarding

.DESCRIPTION
    Onboards a session host VM into an AVD Hybrid Environments host pool.
    Run this script on EACH machine you want to add as a session host.

    This script:
      - Sets the PowerShell execution policy
      - Loads all configuration from AVD-SessionHost-Config.txt
      - Pre-installs the RDSH role on Windows Server (avoids mid-deploy reboot)
      - Downloads and installs the Azure Arc Connected Machine agent
      - Connects the Arc agent to Azure using a service principal
      - Deploys the AVD CloudDeviceExtension to register the machine as a session host
      - Validates the session host appears as Available in the host pool

    Place this script and AVD-SessionHost-Config.txt in the same folder on the VM.
    AVD-SessionHost-Config.txt is generated automatically by Deploy-AVDHybrid-Greenfield.ps1.

.PARAMETER None
    All configuration is loaded automatically from AVD-SessionHost-Config.txt.

.EXAMPLE
    # 1. Copy Deploy-AVDHybrid-SessionHost.ps1 and AVD-SessionHost-Config.txt to the VM
    # 2. Open in PowerShell ISE or VS Code (Run as Administrator)
    # 3. Run section by section using F8

.NOTES
    Version:    1.0
    Author:     Dan Bowker
    Blog:       https://bowker.cloud
    GitHub:     https://github.com/bowkercloud

    Supported OS:
      - Windows Server 2016-2025 (VM or physical machine)
      - Windows 11 Enterprise single-session (VM only)
      - Windows 11 Enterprise Multi-Session is NOT supported

    Supported identity types:
      - Microsoft Entra joined
      - Active Directory Domain Services (ADDS) joined
      - Hybrid Entra joined

    Prerequisites:
      - Run as Administrator
      - AVD-SessionHost-Config.txt in the same folder as this script
      - Outbound internet access to Azure and AVD endpoints
      - Registration token must not be expired (valid 24h from Greenfield script run)

    References:
      https://learn.microsoft.com/en-us/azure/virtual-desktop/deploy-azure-virtual-desktop-hybrid
      https://learn.microsoft.com/en-us/azure/azure-arc/servers/
#>


# =============================================================================
# SECTION 0a - EXECUTION POLICY
# Ensures PowerShell can run this script. Run this section first.
# =============================================================================

$currentPolicy = Get-ExecutionPolicy -Scope CurrentUser
if ($currentPolicy -notin @("RemoteSigned", "Unrestricted", "Bypass")) {
    Write-Host "Setting execution policy to RemoteSigned for current user..." -ForegroundColor Yellow
    Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
    Write-Host "Execution policy set." -ForegroundColor Green
} else {
    Write-Host "Execution policy already set to $currentPolicy. No change needed." -ForegroundColor Green
}


# =============================================================================
# SECTION 0b - LOAD CONFIG FILE
# Reads all variables from AVD-SessionHost-Config.txt which sits in the
# same folder as this script. Generated by the Greenfield script.
# =============================================================================

# Assumes AVD-SessionHost-Config.txt is in the same folder as this script
$ConfigFilePath = Join-Path $PSScriptRoot "AVD-SessionHost-Config.txt"

# -- Load config from file --
if (-not (Test-Path $ConfigFilePath)) {
    throw "Config file not found at $ConfigFilePath. Copy AVD-SessionHost-Config.txt to this VM first."
}

Write-Host "Loading config from $ConfigFilePath..." -ForegroundColor Yellow
$config = @{}
Get-Content $ConfigFilePath | Where-Object { $_ -match "^\s*\w+ \s*=" } | ForEach-Object {
    $parts = $_ -split "\s*=\s*", 2
    $config[$parts[0].Trim()] = $parts[1].Trim()
}

$TenantId          = $config["TenantId"]
$SubscriptionId    = $config["SubscriptionId"]
$Arc_RG            = $config["Arc_RG"]
$Arc_Location      = $config["Arc_Location"]
$AVD_RG            = $config["AVD_RG"]
$HostPoolName      = $config["HostPoolName"]
$SPAppId           = $config["SPAppId"]
$SPSecret          = $config["SPSecret"]
$RegistrationToken = $config["RegistrationToken"]
$TokenExpiry       = $config["TokenExpiry"]

# Validate all required values loaded
$missing = @("TenantId","SubscriptionId","Arc_RG","Arc_Location","AVD_RG","HostPoolName","SPAppId","SPSecret","RegistrationToken") |
    Where-Object { -not $config[$_] }
if ($missing) {
    throw "Missing values in config file: $($missing -join ', '). Regenerate the config file using the Greenfield script."
}

# Warn if registration token is close to expiry or already expired
# Parse expiry date flexibly to handle different timestamp formats
try {
    $expiryDate = [datetime]::Parse($TokenExpiry, [System.Globalization.CultureInfo]::InvariantCulture)
} catch {
    Write-Host "WARNING: Could not parse token expiry date '$TokenExpiry'. Skipping expiry check." -ForegroundColor Yellow
    $expiryDate = (Get-Date).ToUniversalTime().AddHours(24)
}
$hoursLeft  = ($expiryDate - (Get-Date).ToUniversalTime()).TotalHours
if ($hoursLeft -lt 0) {
    Write-Host "WARNING: Registration token expired $([math]::Abs([math]::Round($hoursLeft,1))) hours ago." -ForegroundColor Red
    Write-Host "Re-run Section 8 of the Greenfield script to generate a new token." -ForegroundColor Red
    throw "Stopping - expired registration token. Get a fresh token before continuing."
} elseif ($hoursLeft -lt 4) {
    Write-Host "WARNING: Registration token expires in $([math]::Round($hoursLeft,1)) hours. Consider regenerating." -ForegroundColor Yellow
} else {
    Write-Host "Config loaded successfully. Token valid for $([math]::Round($hoursLeft,1)) more hours." -ForegroundColor Green
}

# This machine's name - will be used as the Arc resource name in Azure
# Defaults to the machine's hostname - change if you want a different name
$MachineName = $env:COMPUTERNAME


# =============================================================================
# SECTION 1 - PRE-INSTALL RDSH ROLE (WINDOWS SERVER ONLY)
# Installing this before the AVD extension avoids an automatic reboot
# mid-deployment. Skip this section if running on Windows 11.
# =============================================================================

$osCaption = (Get-WmiObject Win32_OperatingSystem).Caption
if ($osCaption -like "*Server*") {
    Write-Host "Windows Server detected. Pre-installing RDSH role..." -ForegroundColor Yellow
    $result = Install-WindowsFeature -Name RDS-RD-Server -IncludeManagementTools
    if ($result.RestartNeeded -eq "Yes") {
        Write-Host "RDSH role installed. A restart is required before continuing." -ForegroundColor Yellow
        Write-Host "Please restart the VM and then re-run from Section 2." -ForegroundColor Yellow
        Read-Host "Press Enter to restart now, or Ctrl+C to restart manually later"
        Restart-Computer -Force
    } else {
        Write-Host "RDSH role installed successfully. No restart needed." -ForegroundColor Green
    }
} else {
    Write-Host "Windows 11 detected. Skipping RDSH role install." -ForegroundColor Green
}


# =============================================================================
# SECTION 2 - INSTALL AZURE ARC CONNECTED MACHINE AGENT
# Downloads and installs the Arc agent on this machine.
# Skip this section if the Arc agent is already installed.
# =============================================================================

# Check if already installed
$arcAgentPath = "C:\Program Files\AzureConnectedMachineAgent\azcmagent.exe"
if (Test-Path $arcAgentPath) {
    $version = & $arcAgentPath version
    Write-Host "Arc agent already installed: $version" -ForegroundColor Green
    Write-Host "Skipping installation. Proceeding to Section 3." -ForegroundColor Green
} else {
    Write-Host "Downloading Arc agent..." -ForegroundColor Yellow
    $installer = "$env:TEMP\AzureConnectedMachineAgent.msi"
    Invoke-WebRequest -Uri "https://aka.ms/AzureConnectedMachineAgent" -OutFile $installer
    Write-Host "Installing Arc agent..." -ForegroundColor Yellow
    Start-Process msiexec.exe -ArgumentList "/i $installer /l*v $env:TEMP\ArcInstall.log /qn" -Wait
    if (Test-Path $arcAgentPath) {
        $version = & $arcAgentPath version
        Write-Host "Arc agent installed successfully: $version" -ForegroundColor Green
    } else {
        Write-Host "Arc agent installation may have failed. Check $env:TEMP\ArcInstall.log" -ForegroundColor Red
        throw "Stopping - Arc agent not found after installation."
    }
}


# =============================================================================
# SECTION 3 - CONNECT ARC AGENT TO AZURE
# Checks both connection status AND tenant to avoid skipping on a stale or
# wrong-tenant connection. Disconnects and reconnects automatically if needed.
# =============================================================================

# Parse agent status and tenant properly
$agentShowOutput  = & $arcAgentPath show 2>$null
$agentStatusValue = ($agentShowOutput | Where-Object { $_ -match "Agent Status" } | Select-Object -First 1) -replace ".*:\s*",""
$agentTenantValue = ($agentShowOutput | Where-Object { $_ -match "Tenant ID" } | Select-Object -First 1) -replace ".*:\s*",""

Write-Host "Arc agent status: $agentStatusValue" -ForegroundColor Cyan
Write-Host "Arc agent tenant: $agentTenantValue" -ForegroundColor Cyan

$alreadyConnected = ($agentStatusValue.Trim() -eq "Connected") -and ($agentTenantValue.Trim() -eq $TenantId)

if ($alreadyConnected) {
    Write-Host "Arc agent already connected to the correct tenant. Skipping." -ForegroundColor Green
} else {
    if ($agentStatusValue.Trim() -eq "Connected" -and $agentTenantValue.Trim() -ne $TenantId) {
        Write-Host "Arc agent connected to a different tenant ($agentTenantValue). Disconnecting first..." -ForegroundColor Yellow
        & $arcAgentPath disconnect --service-principal-id $SPAppId --service-principal-secret $SPSecret
        Start-Sleep -Seconds 5
    }

    Write-Host "Connecting Arc agent to Azure..." -ForegroundColor Yellow
    & $arcAgentPath connect `
        --tenant-id                $TenantId `
        --subscription-id          $SubscriptionId `
        --resource-group           $Arc_RG `
        --location                 $Arc_Location `
        --service-principal-id     $SPAppId `
        --service-principal-secret $SPSecret `
        --resource-name            $MachineName

    # Verify connection
    $agentShowOutput  = & $arcAgentPath show 2>$null
    $agentStatusValue = ($agentShowOutput | Where-Object { $_ -match "Agent Status" } | Select-Object -First 1) -replace ".*:\s*",""

    if ($agentStatusValue.Trim() -eq "Connected") {
        Write-Host "Arc agent connected successfully." -ForegroundColor Green
    } else {
        Write-Host "Arc agent connection failed. Status: $agentStatusValue" -ForegroundColor Red
        Write-Host "Check Arc agent logs at: C:\ProgramData\AzureConnectedMachineAgent\Log\" -ForegroundColor Yellow
        throw "Stopping - Arc agent not connected. Resolve before continuing."
    }
}


# =============================================================================
# SECTION 4 - DEPLOY THE AVD ARC EXTENSION
# Installs AVD components and registers this machine as a session host.
# It can take up to 15 minutes after install for the host to appear as Available.
#
# NOTE: If the registration token has expired (> 24 hours), re-run Section 8
# of the Greenfield script to regenerate it and copy the updated config file.
# =============================================================================

# Ensure NuGet provider is available silently (avoids interactive prompt)
if (-not (Get-PackageProvider -Name NuGet -ErrorAction SilentlyContinue | Where-Object { $_.Version -ge "2.8.5.201" })) {
    Write-Host "Installing NuGet provider..." -ForegroundColor Yellow
    Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force -Scope CurrentUser | Out-Null
    Write-Host "NuGet provider installed." -ForegroundColor Green
} else {
    Write-Host "NuGet provider already installed." -ForegroundColor Green
}

# Install Az modules needed for extension deployment and validation
$modules = @('Az.Accounts', 'Az.ConnectedMachine', 'Az.DesktopVirtualization')
foreach ($m in $modules) {
    if (-not (Get-Module -ListAvailable -Name $m)) {
        Write-Host "Installing $m..." -ForegroundColor Yellow
        Install-Module $m -Scope CurrentUser -Repository PSGallery -Force -AllowClobber -ErrorAction Stop
    }
    Import-Module $m -ErrorAction Stop
}

# Sign in to Azure (browser window will open)
Connect-AzAccount -TenantId $TenantId
Select-AzSubscription -SubscriptionId $SubscriptionId

# Deploy the extension
$ExtPublisher = "Microsoft.AzureVirtualDesktop"
$ExtType      = "CloudDeviceExtension"
$ExtName      = "$ExtPublisher.$ExtType"

Write-Host "Deploying AVD Arc extension to $MachineName..." -ForegroundColor Yellow

New-AzConnectedMachineExtension `
    -Name              $ExtName `
    -ResourceGroupName $Arc_RG `
    -MachineName       $MachineName `
    -Location          $Arc_Location `
    -Publisher         $ExtPublisher `
    -ExtensionType     $ExtType `
    -Setting           @{ isCloudDevice = $false } `
    -ProtectedSetting  @{ registrationToken = $RegistrationToken } `
    -ErrorAction Stop

Write-Host "Extension deployed to $MachineName." -ForegroundColor Green
Write-Host "Waiting up to 15 minutes for session host to appear as Available in the host pool..." -ForegroundColor Yellow


# =============================================================================
# SECTION 5 - VALIDATE SESSION HOST REGISTRATION
# Run after waiting ~15 minutes.
# =============================================================================

# Check extension provisioning state
$extState = (Get-AzConnectedMachineExtension `
    -ResourceGroupName $Arc_RG `
    -MachineName       $MachineName `
    -Name              $ExtName).ProvisioningState

Write-Host "Extension provisioning state: $extState" -ForegroundColor Cyan

# Check session host status in the host pool
$sessionHost = Get-AzWvdSessionHost `
    -ResourceGroupName $AVD_RG `
    -HostPoolName      $HostPoolName | `
    Where-Object { $_.Name -like "*$MachineName*" }

if ($sessionHost) {
    Write-Host "Session host found in host pool:" -ForegroundColor Green
    $sessionHost | Select-Object Name, Status, LastHeartBeat | Format-List
    if ($sessionHost.Status -eq "Available") {
        Write-Host "$MachineName is Available and ready for users." -ForegroundColor Green
    } else {
        Write-Host "Status is '$($sessionHost.Status)'. This may still be initialising - check again in a few minutes." -ForegroundColor Yellow
    }
} else {
    Write-Host "$MachineName not yet visible in host pool. Wait a few more minutes and re-run Section 5." -ForegroundColor Yellow
    Write-Host "You can also check in the Azure portal: Azure Virtual Desktop > Host pools > $HostPoolName > Session hosts" -ForegroundColor Yellow
}
